version: "1"

services:
  database:
    image: database_todo
    environment:
      POSTGRES_DB: docker_app_db
      POSTGRES_USER: docker_app
      POSTGRES_PASSWORD: docker_app
    volumes:
      - volume_todo:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 3


  backend:
    image: backend_todo
    environment:
      HOST: database
      PORT: 5432
      DB: docker_app_db
      DB_USERNAME: docker_app
      DB_PASSWORD: docker_app
    healthcheck:
      test: ["CMD", "curl", "localhost:8000/test"]
      interval: 5s
      timeout: 5s
      retries: 3

    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx_todo
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  volume_todo:
